alias v='nvim'
alias vi='nvim'
alias view='nvim -MR'
alias ls='exa'
alias la='exa --all'
alias ll='exa --long'
alias lla='exa --all --long'
alias cat='bat --style=plain --theme=OneHalfDark'
alias zshconfig='vi ~/.zshrc'
alias tmuxconfig='vi ~/.tmux.conf'
alias viconf='vi ~/.config/nvim/init.vim'
alias conf='cd ~/.config'
alias tmuxn='tmux new -s'
alias tmuxa='tmux a -t'
alias tmuxl='tmux ls'
alias st='stree'
alias gh='github'
# alias ssh='sshrc'
alias d="docker"
alias dps="d ps" #=docker container ls
alias dpa="d ps -a"
alias di="d image"
alias dip="d image prune"
alias dis="d images --digests"
alias db="d bulid"
alias dex="d exec -i -t"
alias dsp="d system prune"
alias dl="d pull"
alias k='kubectl'
alias kc='kubectx'
alias knife='chef exec knife'
