# alias ssh='sshrc'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias cd='(){builtin cd "$@" && ls}'
alias cat='bat --style=plain'
alias cfg='(){cd $XDG_CONFIG_HOME/$1}'
alias d="docker"
alias db="d bulid"
alias dex="d exec -i -t"
alias di="d image"
alias dip="d image prune"
alias dis="d images --digests"
alias dl="d pull"
alias dpa="d ps -a"
alias dps="d ps" #=docker container ls
alias dsp="d system prune"
alias gh='github'
alias k='kubectl'
alias kc='kubectx'
alias knife='chef exec knife'
alias la='exa --all'
alias ll='exa --long'
alias lla='exa --all --long'
alias ls='exa'
alias st='stree'
alias tmuxa='tmux a -t'
alias tmuxl='tmux ls'
alias tmuxn='tmux new -s'
alias v='nvim'
alias vi='nvim'
alias view='nvim -MR'
