for file in $XDG_CONFIG_HOME/zsh/*.zsh; do
  source $file
done

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'

touch ~/.hushlogin

key=$(ssh-add -l)
if [ ${key} = 'The agent has no identities.' ] && [ -e ~/.ssh/id_rsa ]; then
  ssh-add --apple-use-keychain
fi

if [ -f $(brew --prefix)/etc/brew-wrap ];then
  source $(brew --prefix)/etc/brew-wrap
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(starship init zsh)"
