## Shell:
# setopt auto_cd
# setopt auto_list
# setopt auto_menu
# autoload -U compinit; compinit
function custom_cd() {
  \cd $@ && ls 
}
alias cd='custom_cd'
## linuxbrew
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
## anyenv
# eval "$(anyenv init -)"

## Alias:
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
# neovim
# which nvim > /dev/null 2>&1 && alias v='nvim' && alias vi='nvim'
if type nvim > /dev/null 2>&1; then
  alias v='nvim' && alias vi='nvim'
else
  alias v='vim' && alias vi='vim'
fi
# git alias
alias g='git'
alias ga='git add'
alias gb='git branch'
alias gba='git branch -a'
alias gcmsg='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gl='git pull'
alias gp='git push'
alias grhh='git reset --hard HEAD'
# tmux
alias tmuxa='tmux a -t'
alias tmuxl='tmux ls'
# docker alias
alias d="sudo docker"
alias dps="d ps" #=docker container ls
alias dpa="d ps -a"
alias di="d image"
alias dip="d image prune"
alias dis="d images"
alias db="d bulid"
alias dex="d exec -i -t"
alias dsp="d system prune"
alias dl="d pull"
# docker-compose alias
alias dc="sudo docker-compose"
