#---------------------------------------------------------------------------
# HTML5+CSS3:
#

# HTML5 omnicomplete and syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

# Add CSS3 syntax support
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
# on_ft = 'css'

# Preview colours in source code
[[plugins]]
repo = 'ap/vim-css-color'
# on_ft = 'css'

# emmet for vim
[[plugins]]
repo = 'mattn/emmet-vim'
# on_ft = ['html', 'css', 'javascript', 'php']

# Auto close (X)HTML tags
[[plugins]]
repo = 'alvan/vim-closetag'

# A Vim plugin that always highlights the enclosing html/xml tags
[[plugins]]
repo = 'valloric/matchtagalways'
on_ft = ['html', 'xml']

# Context filetype library for Vim script
[[plugins]]
repo = "Shougo/context_filetype.vim"
# on_ft = ['html', 'markdown']

#---------------------------------------------------------------------------
# Javascript:
#

# Vastly improved Javascript indentation and syntax support in Vim
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

# A semantic javascript syntax highlighter (uses babylon) for Neovim
# [[plugins]]
# repo = 'billyvg/tigris.nvim'
# on_ft = ['javascript', 'javascript.jsx']
# build = './install.sh'

# React JSX syntax pretty highlighting for vim.
# [[plugins]]
# repo = 'MaxMEllon/vim-jsx-pretty'
# on_ft = ['javascript.jsx', 'typescript.tsx']

# Syntax and indent plugin for React jsx.
# [[plugins]]
# repo = 'neoclide/vim-jsx-improve'
# on_ft = ['javascript', 'javascript.jsx']

# YAJS.vim: Yet Another JavaScript Syntax for Vim
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

# ES.Next syntax for Vim
[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

# Syntax for JavaScript libraries
# [[plugins]]
# repo = 'othree/javascript-libraries-syntax.vim'
# on_ft = ['javascript', 'javascript.jsx']

# JavaScript indentation for VIM
# [[plugins]]
# repo = 'gavocanov/vim-js-indent'
# on_ft = ['javascript', 'javascript.jsx']

# Tern plugin for Vim
[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = ['javascript', 'javascript.jsx']
build = 'npm install'

# deoplete.nvim source for javascript
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript', 'javascript.jsx']
build = 'npm install -g tern'

# Syntax Highligth for Vue.js components
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['javascript', 'vue']

# Generate JSDoc to your JavaScript code.
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = ['javascript', 'javascript.jsx']

# Tools and environment to make Vim superb for developing with Node.js. Like Rails.vim for Node.
[[plugins]]
repo = 'moll/vim-node'
on_ft = 'javascript'

# Vim bundle for http://styled-components.com based javascript files.
[[plugins]]
repo = 'styled-components/vim-styled-components'
# repo = 'tomaskallup/vim-styled-components'
on_ft = ['javascript.jsx', 'typescript.tsx']
rev = 'main'

# A Vim plugin that provides GraphQL file detection, syntax highlighting, and indentation.
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['javascript.jsx', 'typescript.tsx']

#---------------------------------------------------------------------------
# Typescript:
#

# Typescript syntax files for Vim
# [[plugins]]
# repo = 'leafgarland/typescript-vim'
# on_ft = ['typescript']

# Typescript tooling for Neovim
# [[plugins]]
# repo = 'mhartington/nvim-typescript'
# on_ft = ['typescript', 'typescript.tsx']
# build = './install.sh' # And try to run :UpdateRemotePlugins if you havn't already.

# Yet Another TypeScript Syntax: The most advanced TypeScript Syntax Highlighting in Vim
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx']

# React JSX syntax highlighting for vim and Typescript
# [[plugins]]
# repo = 'peitalin/vim-jsx-typescript'
# on_ft = ['typescript', 'typescript.tsx']

#---------------------------------------------------------------------------
# Go:
#

# Go development plugin for Vim
# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'

# Asynchronous Go completion for Neovim. deoplete source for Go.
# [[plugins]]
# repo = 'deoplete-plugins/deoplete-go'
# build = 'make'
# on_ft = 'go'
# on_event = 'InsertEnter'
# depends = ['deoplete.nvim']

#---------------------------------------------------------------------------
# Dart:
#

# Syntax highlighting for Dart in Vim
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

#---------------------------------------------------------------------------
# YAML:
#

# Add additional support for Ansible in VIM
[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = 'ansible'

#---------------------------------------------------------------------------
# Markdown:
#

# VIM Table Mode for instant table creation.
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'

# Realtime preview by Vim. (Markdown, reStructuredText, textile)
[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'

#---------------------------------------------------------------------------
# Json:
#

# A better JSON for Vim: distinct highlighting of keywords vs values, JSON-specific (non-JS) warnings, quote concealing. Pathogen-friendly.
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

#---------------------------------------------------------------------------
# Toml:
#

# Vim syntax for TOML.
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml', 'conf']

#---------------------------------------------------------------------------
# Docker:
#

# Vim syntax file & snippets for Docker's Dockerfile
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

#---------------------------------------------------------------------------
# UML:
#

# Inline previews for Plantuml sequence diagrams. OMG!
# [[plugins]]
# repo = 'scrooloose/vim-slumlord'
# on_ft = 'plantuml'

# Vim plugin for preview Plantuml
[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'
on_ft = 'plantuml'

# vim syntax file for plantuml
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

#---------------------------------------------------------------------------
# LaTex:
#

# A modern vim plugin for editing LaTeX files.
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'plaintex']
