# Insert several candidates with a single key
[[plugins]]
repo = 'kana/vim-smartchr'
on_event = 'InsertEnter'

# An eye friendly plugin that fades your inactive buffers and preserves your syntax highlighting!
[[plugins]]
repo = 'TaDaa/vimade'
on_event = 'WinNew'

#---------------------------------------------------------------------------
# Nerdtree:
#

# A tree explorer
[[plugins]]
repo = 'scrooloose/nerdtree'
on_event = 'NERDTreeToggle'

# NERDTree and tabs together
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
on_event = 'NERDTreeToggle'

# Extra syntax and highlight for nerdtree files
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
on_event = 'NERDTreeToggle'

# Changes Vim working directory to project root (identified by presence of known directory or file).
[[plugins]]
repo = 'airblade/vim-rooter'
on_event = 'NERDTreeToggle'
