# Dark powered Vim/Neovim plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Intellisense engine for vim8 & neovim, full language server protocol support as VSCode
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

# File-type sensible comments
[[plugins]]
repo = 'tomtom/tcomment_vim'

# Delete/change/add parentheses/quotes/XML-tags/much more with ease
[[plugins]]
repo = 'tpope/vim-surround'

# Asynchronous Lint Engine
[[plugins]]
repo = 'w0rp/ale'

# ALE indicator for the lightline vim plugin
[[plugins]]
repo = 'maximbaz/lightline-ale'

# Open URI with your favorite browser
[[plugins]]
repo = 'tyru/open-browser.vim'

# Easy and high speed coding method
[[plugins]]
repo = 'mattn/sonictemplate-vim'

# responsive tabline
[[plugins]]
repo = 'yami-beta/vim-responsive-tabline'

# Insert or delete brackets, parens, quotes in pair
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# Vim motions on speed!
[[plugins]]
repo = 'easymotion/vim-easymotion'

# fzf
[[plugins]]
repo = '/usr/local/opt/fzf'

# fzf-vim
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# A Git wrapper so awesome, it should be illegal
# [[plugins]]
# repo = 'tpope/vim-fugitive'

# A Vim plugin for indent-level based motion.
[[plugins]]
repo = 'jeetsukumaran/vim-indentwise'

# Show / hide cursorline automatically
[[plugins]]
repo = 'yamatsum/vim-auto-cursorline'

# Underlines the word under the cursor
[[plugins]]
repo = 'yamatsum/vim-cursorword'

#---------------------------------------------------------------------------
# View:
#

# A light and configurable statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

# Provides the branch name of the current git repository
[[plugins]]
repo = 'itchyny/vim-gitbranch'

# Displaying the indention levels with thin vertical lines
[[plugins]]
repo = 'Yggdroot/indentLine'

# Highlights trailing whitespace in red and provides :FixWhitespace to fix it.
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Adds filetype glyphs (icons) to other plugins such as NERDTree, lightline.vim
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# A Vim plugin which shows a git diff in the gutter (sign column) and stages/undoes hunks.
[[plugins]]
repo = 'airblade/vim-gitgutter'

#---------------------------------------------------------------------------
# ColorScheme:
#

# A dark Vim/Neovim color scheme inspired by Atom's One Dark syntax theme.
[[plugins]]
repo = 'joshdick/onedark.vim'
