# Snippet support
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# The standard snippets repository for neosnippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

# Dark powered asynchronous completion framework for neovim/Vim8
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1

