# Dark powered asynchronous unite all interfaces for neovim
[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

# Simple templates plugin
[[plugins]]
repo = 'aperezdc/vim-template'

# Run commands quickly.
[[plugins]]
repo = 'thinca/vim-quickrun'

# search status
[[plugins]]
repo = 'osyo-manga/vim-anzu'

# Vim plugin to dim inactive windows
[[plugins]]
repo = 'blueyed/vim-diminactive'

# Distraction-free writing in Vim
[[plugins]]
repo = 'junegunn/goyo.vim'

# Plugin to toggle, display and navigate marks
[[plugins]]
repo = 'kshenoy/vim-signature'

# Deoplete source for emoji codes
[[plugins]]
repo = 'fszymanski/deoplete-emoji'

# Syntax source for neocomplete/deoplete/ncm
[[plugins]]
repo = 'Shougo/neco-syntax'

# Brings physics-based smooth scrolling to the Vim world!
[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

# Vim plugin that displays tags in a window, ordered by scope
[[plugins]]
repo = 'majutsushi/tagbar'

# edit evernote on vim.
[[plugins]]
repo = 'kakkyz81/evervim'

# Changes the splash of Vim as you like.
[[plugins]]
repo = 'thinca/vim-splash'

# The interactive scratchpad for hackers.
[[plugins]]
repo = 'metakirby5/codi.vim'

# A simple task and time manager for vim.
[[plugins]]
repo = 'soywod/kronos.vim'

# Show / hide cursorline automatically
[[plugins]]
repo = 'delphinus/vim-auto-cursorline'

# Search Dash.app [\d]
[[plugins]]
repo = 'rizzatti/dash.vim'

# A plugin of NERDTree showing git status
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

#---------------------------------------------------------------------------
# Test:
#

# asynchronous build and test dispatcher
[[plugins]]
repo = 'tpope/vim-dispatch'

# Run your tests at the speed of thought
[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']

#---------------------------------------------------------------------------
# ColorScheme:
#

# Generate a beautiful color swatch of the current color scheme
[[plugins]]
repo = 'cocopon/colorswatch.vim'

# Material theme for vim
[[plugins]]
repo = 'jdkanani/vim-material-theme'

# A vim theme inspired by Atom's default dark theme
[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

# Monokai color scheme for Vim converted from Textmate theme
[[plugins]]
repo = 'sickill/vim-monokai'

# Oceanic Next theme for neovim
[[plugins]]
repo = 'mhartington/oceanic-next'

# A 24bit colorscheme for Vim, Airline and Lightline
[[plugins]]
repo = 'jacoborus/tender'

# Adaptation of one-light and one-dark colorschemes for Vim
[[plugins]]
repo = 'rakr/vim-one'
