ZSH_THEME="spaceship"

SPACESHIP_CHAR_SYMBOL='❯ '
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_GIT_BRANCH_PREFIX=' '
SPACESHIP_GIT_STATUS_PREFIX=' ['
SPACESHIP_GIT_STATUS_SUFFIX=']'
SPACESHIP_GIT_STATUS_ADDED=' '
SPACESHIP_GIT_STATUS_MODIFIED=' '
SPACESHIP_GIT_STATUS_RENAMED=' '
SPACESHIP_GIT_STATUS_DELETED=' '
SPACESHIP_GIT_STATUS_AHEAD=' ' # 
SPACESHIP_GIT_STATUS_BEHIND=' ' # 
SPACESHIP_PACKAGE_SYMBOL=' ' # 
SPACESHIP_NODE_SYMBOL=' '
SPACESHIP_RUBY_SYMBOL=' ' #  
SPACESHIP_GOLANG_SYMBOL=' ' # 
SPACESHIP_PHP_SYMBOL=' '
SPACESHIP_DOCKER_SYMBOL=' '
SPACESHIP_PYENV_SYMBOL=' '

