[git_branch]
symbol = " "
[golang]
symbol = " "
[nodejs]
symbol = " "
[package]
symbol = " "
[python]
symbol = " "
[ruby]
symbol = " "
[lua]
symbol = " "
[git_commit]
disabled = true
[git_status]
disabled = true
[battery]
disabled = true
[gcloud]
disabled = true
